/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Copy for the branch-operations consoles.
 *
 * This follows the customer app's pattern (`apps/mobile/src/i18n/strings.ts`):
 * one typed table, keys grouped by area, looked up through a function. It does
 * NOT follow the admin console's `isRTL ? '…' : '…'` inline ternaries, which
 * are unreviewable at volume and have already left several admin surfaces
 * English-only.
 *
 * Arabic is written first in each pair because Arabic is the default for these
 * consoles — the people using them work the counter and the phones.
 */
export type OpsLang = 'ar' | 'en';

export const OPS_STRINGS = {
  ar: {
    // shell
    branchConsole: 'لوحة الفرع',
    callCentreConsole: 'لوحة مركز الاتصال',
    signOut: 'تسجيل الخروج',
    language: 'English',
    refresh: 'تحديث',
    loading: 'جارٍ التحميل…',
    retry: 'إعادة المحاولة',
    noBranchTitle: 'لم يتم ربط حسابك بفرع',
    noBranchBody: 'تواصل مع المسؤول لربط حسابك بالفرع الذي تعمل فيه.',
    loadFailed: 'تعذّر تحميل البيانات',
    branchClosed: 'الفرع مغلق حالياً',
    callCentreScope: 'حسابك يتابع إغلاقات جميع الفروع.',

    // sections
    closedNow: 'الأصناف الموقوفة',
    closedNoneTitle: 'كل الأصناف متاحة',
    closedNoneBody: 'لا يوجد أي صنف موقوف في فرعك الآن.',
    closedSizesOnlyTitle: 'كل الأصناف متاحة، لكن هناك أحجام موقوفة',
    sizeBlockedTitle: 'أصناف لا يمكن طلبها — كل أحجامها موقوفة',
    sizeBlockedBody: 'أوقفت كل أحجام صنف أو أكثر، فلم يعد بالإمكان طلبه إطلاقاً. أعد إتاحة حجم واحد على الأقل.',
    closedSizesOnlyBody: 'لا يوجد صنف موقوف بالكامل، لكن بعض الأحجام موقوفة — انظر قائمة الأحجام الموقوفة أدناه.',
    allItems: 'كل الأصناف',
    searchPlaceholder: 'ابحث عن صنف…',
    noResults: 'لا توجد نتائج مطابقة.',
    uncategorized: 'بدون تصنيف',

    // actions
    close: 'إيقاف',
    reopen: 'إتاحة',
    cancel: 'إلغاء',
    confirmClose: 'تأكيد الإيقاف',
    working: 'جارٍ التنفيذ…',

    // close dialog
    closeTitle: 'إيقاف الصنف مؤقتاً',
    durationLabel: 'المدة',
    reasonLabel: 'السبب',
    noteLabel: 'ملاحظة (اختياري)',
    notePlaceholder: 'تفاصيل إضافية…',
    autoReopenHint: 'سيعود الصنف تلقائياً عند انتهاء المدة.',

    // durations
    dur30m: '30 دقيقة',
    dur1h: 'ساعة',
    dur3h: '3 ساعات',
    dur6h: '6 ساعات',
    dur12h: '12 ساعة',

    // reasons
    reason_out_of_stock: 'نفد المخزون',
    reason_supplier_delay: 'تأخر المورد',
    reason_equipment_down: 'عطل في المعدات',
    reason_quality_hold: 'إيقاف للجودة',
    reason_other: 'سبب آخر',

    // options (modifiers — Lazywait calls them Prices)
    optionsLabel: 'الخيارات',
    showOptions: 'عرض الخيارات',
    hideOptions: 'إخفاء الخيارات',
    noOptions: 'لا توجد خيارات لهذا الصنف.',
    closedOptions: 'الخيارات الموقوفة',
    closedSizes: 'الأحجام الموقوفة',
    closeOptionTitle: 'إيقاف الخيار مؤقتاً',
    optionAutoReopenHint: 'سيعود الخيار تلقائياً عند انتهاء المدة.',
    closeSizeTitle: 'إيقاف الحجم مؤقتاً',
    sizeAutoReopenHint: 'سيعود الحجم تلقائياً عند انتهاء المدة.',
    requiredGroup: 'إلزامي',
    optionalGroup: 'اختياري',
    blockedByOptions: 'الصنف غير قابل للطلب: مجموعة إلزامية لا تحتوي على خيار متاح.',

    // countdown
    backIn: 'يعود خلال',
    reopeningNow: 'يعود الآن',
    untimed: 'موقوف بدون مدة',

    blockedItemsLabel: 'أصناف لا يمكن طلبها',
    blockedCausesLabel: 'سبب التعذّر',
    blockedReasonPill: 'خيار إلزامي موقوف',
    blockedByGroup: 'مجموعة إلزامية نفدت خياراتها',
    blockedCountLabel: 'أصناف متعذّرة',
    itemsUnavailableCount: 'أصناف غير متاحة',
    sizesClosedCount: 'أحجام موقوفة',
    closedSizesLabel: 'أحجام موقوفة',
    sizeBlockedLabel: 'أصناف موقوفة بسبب إيقاف كل أحجامها',
    returnLapsed: 'يعود الآن',
    optionsClosedCount: 'خيارات موقوفة',
    affectedCount: 'صنف متأثر',
    earliestReturn: 'أقرب عودة',
    returnUnknown: 'وقت العودة غير محدد',
    viewOnlyOptionsNote: 'إعادة فتح الخيار من صلاحية الفرع وحده.',
    optionOnlyTitle: 'فروع بخيارات موقوفة فقط',
    optionOnlyBody: 'كل الأصناف ما زالت قابلة للطلب في هذه الفروع.',

    // call-centre board
    boardAllClearTitle: 'كل الفروع تعمل بشكل طبيعي',
    boardAllClearBody: 'لا يوجد أي صنف موقوف أو توصيل متوقف الآن.',
    boardNeedsAttention: 'فروع تحتاج متابعة',
    itemsClosedCount: 'أصناف موقوفة',
    areasDisabledCount: 'مناطق موقوفة',
    deliveryPausedLabel: 'التوصيل متوقف',
    deliveryRunningLabel: 'التوصيل يعمل',
    resumeDelivery: 'استئناف التوصيل',
    deliveryResumesIn: 'يستأنف التوصيل خلال',
    deliveryResumingNow: 'يستأنف الآن',
    deliveryPausedUntimed: 'موقوف بدون مدة',
    openBranch: 'عرض التفاصيل',
    closePanel: 'إغلاق',
    contactLabel: 'التواصل',
    workingHoursLabel: 'ساعات العمل',
    areasLabel: 'مناطق التوصيل',
    closedItemsLabel: 'الأصناف الموقوفة',
    enableArea: 'تفعيل',
    disableArea: 'إيقاف',
    soundOn: 'التنبيه الصوتي مفعّل',
    soundOff: 'التنبيه الصوتي مكتوم',
    newClosure: 'إغلاق جديد',
    advisoryAreasNote: 'أسماء المناطق مرجع لمركز الاتصال فقط ولا تتحكم في التطبيق.',

    // delivery pause
    pauseDeliveryTitle: 'إيقاف التوصيل مؤقتاً',
    pauseDelivery: 'إيقاف التوصيل لمدة…',
    confirmPause: 'تأكيد الإيقاف',
    deliveryAutoResumeHint: 'سيعود التوصيل تلقائياً عند انتهاء المدة. الاستلام من الفرع لا يتأثر.',
    dreason_no_driver: 'لا يوجد سائق',
    dreason_weather: 'الطقس',
    dreason_kitchen_overload: 'ضغط على المطبخ',
    dreason_area_incident: 'ظرف في المنطقة',
    dreason_other: 'سبب آخر',

    // sign-in
    authSignInTitle: 'تسجيل الدخول إلى حسابك',
    authSignUpTitle: 'إنشاء حساب جديد',
    authSignIn: 'تسجيل الدخول',
    authSignUp: 'إنشاء حساب',
    authFullName: 'الاسم الكامل',
    authPhone: 'رقم الجوال (اختياري)',
    authEmail: 'البريد الإلكتروني',
    authPassword: 'كلمة المرور',
    authWorking: 'جارٍ المتابعة…',
    authFailed: 'تعذّر تسجيل الدخول',

    // delivery-closure requests (branch asks, call centre answers)
    deliveryRequestSection: 'إغلاق التوصيل',
    requestCloseDelivery: 'طلب إغلاق التوصيل',
    requestCloseTitle: 'طلب إغلاق التوصيل',
    confirmRequest: 'إرسال الطلب',
    withdrawRequest: 'سحب الطلب',
    requestWaiting: 'بانتظار رد مركز الاتصال',
    requestWaitingHint: 'التوصيل ما زال يعمل. لن يتوقف إلا بموافقة مركز الاتصال.',
    requestExpiresIn: 'ينتهي الطلب خلال',
    requestMinutesShort: 'د',
    requestAccepted: 'تمت الموافقة على طلبك',
    requestDeclined: 'لم تتم الموافقة على طلبك',
    requestNoneTitle: 'لا يوجد طلب حالي',
    requestNoneBody: 'إذا تعذّر التوصيل، أرسل طلباً إلى مركز الاتصال.',
    requestBlockedClosed: 'التوصيل مغلق بالفعل في فرعك.',
    requestHint: 'إرسال الطلب لا يوقف التوصيل. مركز الاتصال هو من يوقفه.',
    requestSendFailed: 'تعذّر إرسال الطلب',

    // branch reference sheet
    referenceSection: 'معلومات الفرع',
    referenceEmptyTitle: 'لا توجد معلومات محفوظة',
    referenceEmptyBody: 'يضيف المسؤول هنا الأرقام والروابط وبيانات الدخول التي تحتاجها.',
    referenceReveal: 'إظهار',
    referenceHide: 'إخفاء',
    referenceRevealFailed: 'تعذّر إظهار القيمة',
    referenceAuditNotice: 'يُسجَّل كل إظهار لبيانات الدخول: من أظهرها ومتى.',
    referenceCopy: 'نسخ',
    referenceCopied: 'تم النسخ',

    // call-centre: answering a branch's delivery request
    requestsWaiting: 'طلبات بانتظار الرد',
    requestsNoneTitle: 'لا توجد طلبات',
    requestFrom: 'طلب من',
    requestAccept: 'موافقة وإغلاق التوصيل',
    requestDecline: 'رفض',
    requestAnswerFailed: 'تعذّر الرد على الطلب',
    requestNowExpired: 'انتهت صلاحية الطلب قبل الرد عليه',
    requestAskedFor: 'المدة المطلوبة',
    reasonLabelShort: 'السبب',

    // ---- tabs (2026-09-16 redesign) ----
    tabItems: 'الأصناف',
    tabGeneral: 'معلومات عامة',
    tabBranch: 'معلومات الفرع',
    tabDelivery: 'إيقاف التوصيل',

    // ---- items tab ----
    closedCount: 'أصناف موقوفة الآن',
    closedCountOne: 'صنف موقوف الآن',
    autoReopenNote: 'تُتاح تلقائياً عند انتهاء المؤقت',
    reopenAll: 'إتاحة الكل في هذا الفرع',
    reopenAllTitle: 'إتاحة كل الأصناف الموقوفة؟',
    reopenAllBody: 'سيعود كل صنف موقوف في فرعك إلى القائمة فوراً. لا يؤثر هذا على الفروع الأخرى.',
    reopenAllConfirm: 'نعم، أتِح الكل',
    reopenAllFailed: 'تعذّرت إتاحة بعض الأصناف',
    categoryAll: 'الكل',
    stateClosed: 'موقوف',
    partiallyClosed: 'موقوف جزئياً',
    sizesCount: 'أحجام',
    sizesCountOne: 'حجم',
    fromPrice: 'من',
    currency: 'ر.س',

    // ---- variant sheet ----
    sizesTitle: 'الأحجام والأسعار',
    sizesClosedOf: 'موقوف منها',
    closeWholeItem: 'إيقاف الصنف بالكامل',
    done: 'تم',
    sizesPerSizeSoon: 'إيقاف حجم بمفرده غير متاح بعد — إيقاف الصنف يوقف كل أحجامه.',
    sizesAllClosed: 'كل الأحجام موقوفة — لا يمكن للعميل طلب هذا الصنف.',
    sizesPerSizeOffReopenOnly: 'إيقاف حجم بمفرده غير مفعّل هنا، لكن يمكنك إتاحة الأحجام الموقوفة مسبقاً.',
  },
  en: {
    branchConsole: 'Branch Console',
    callCentreConsole: 'Call Centre Console',
    signOut: 'Sign out',
    language: 'العربية',
    refresh: 'Refresh',
    loading: 'Loading…',
    retry: 'Retry',
    noBranchTitle: 'Your account is not linked to a branch',
    noBranchBody: 'Ask an administrator to link your account to the branch you work in.',
    loadFailed: 'Could not load data',
    branchClosed: 'This branch is currently closed',
    callCentreScope: 'Your account monitors closures across every branch.',

    closedNow: 'Closed items',
    closedNoneTitle: 'Everything is available',
    closedNoneBody: 'No item is closed at your branch right now.',
    closedSizesOnlyTitle: 'Every item is available, but some sizes are closed',
    sizeBlockedTitle: 'Some items cannot be ordered — every size is closed',
    sizeBlockedBody: 'Every size of one or more items is closed, so customers cannot order them at all. Reopen at least one size.',
    closedSizesOnlyBody: 'No item is closed outright, but some sizes are — see the closed sizes list below.',
    allItems: 'All items',
    searchPlaceholder: 'Search for an item…',
    noResults: 'No matching items.',
    uncategorized: 'Uncategorized',

    close: 'Close',
    reopen: 'Reopen',
    cancel: 'Cancel',
    confirmClose: 'Confirm closure',
    working: 'Working…',

    closeTitle: 'Close this item temporarily',
    durationLabel: 'Duration',
    reasonLabel: 'Reason',
    noteLabel: 'Note (optional)',
    notePlaceholder: 'Anything worth recording…',
    autoReopenHint: 'The item reopens by itself when the timer runs out.',

    dur30m: '30 minutes',
    dur1h: '1 hour',
    dur3h: '3 hours',
    dur6h: '6 hours',
    dur12h: '12 hours',

    reason_out_of_stock: 'Out of stock',
    reason_supplier_delay: 'Supplier delay',
    reason_equipment_down: 'Equipment down',
    reason_quality_hold: 'Quality hold',
    reason_other: 'Other',

    backIn: 'Back in',
    reopeningNow: 'Reopening now',
    untimed: 'Closed with no timer',

    boardAllClearTitle: 'Every branch is running normally',
    boardAllClearBody: 'Nothing is closed and no delivery is paused right now.',
    boardNeedsAttention: 'Branches needing attention',
    itemsClosedCount: 'items closed',
    areasDisabledCount: 'areas disabled',
    deliveryPausedLabel: 'Delivery paused',
    deliveryRunningLabel: 'Delivery running',
    resumeDelivery: 'Resume delivery',
    deliveryResumesIn: 'Delivery resumes in',
    deliveryResumingNow: 'Resuming now',
    deliveryPausedUntimed: 'Paused with no timer',
    openBranch: 'View details',
    closePanel: 'Close',
    contactLabel: 'Contact',
    workingHoursLabel: 'Working hours',
    areasLabel: 'Delivery areas',
    closedItemsLabel: 'Closed items',
    enableArea: 'Enable',
    disableArea: 'Disable',
    soundOn: 'Alert sound on',
    soundOff: 'Alert sound muted',
    newClosure: 'New closure',
    advisoryAreasNote: 'Area names are call-centre reference only and do not control the app.',

    pauseDeliveryTitle: 'Pause delivery temporarily',
    pauseDelivery: 'Pause delivery for…',
    confirmPause: 'Confirm pause',
    deliveryAutoResumeHint: 'Delivery resumes by itself when the timer runs out. Pickup is unaffected.',
    dreason_no_driver: 'No driver',
    dreason_weather: 'Weather',
    dreason_kitchen_overload: 'Kitchen overloaded',
    dreason_area_incident: 'Incident in the area',
    dreason_other: 'Other',

    optionsLabel: 'Options',
    showOptions: 'Show options',
    hideOptions: 'Hide options',
    noOptions: 'This item has no options.',
    closedOptions: 'Closed options',
    closedSizes: 'Closed sizes',
    closeOptionTitle: 'Close this option',
    optionAutoReopenHint: 'The option reopens by itself when the timer ends.',
    closeSizeTitle: 'Close this size',
    sizeAutoReopenHint: 'The size reopens by itself when the timer ends.',
    requiredGroup: 'Required',
    optionalGroup: 'Optional',
    blockedByOptions: 'Not orderable: a required group has no available option left.',

    blockedItemsLabel: 'Items customers cannot order',
    blockedCausesLabel: 'What is causing it',
    blockedReasonPill: 'Required option closed',
    blockedByGroup: 'a required group has run out',
    blockedCountLabel: 'items blocked',
    itemsUnavailableCount: 'items unavailable',
    sizesClosedCount: 'sizes closed',
    closedSizesLabel: 'Closed sizes',
    sizeBlockedLabel: 'Items blocked because every size is closed',
    returnLapsed: 'Returning now',
    optionsClosedCount: 'options closed',
    affectedCount: 'items affected',
    earliestReturn: 'Earliest return',
    returnUnknown: 'No return time',
    viewOnlyOptionsNote: 'Only the branch can reopen an option.',
    optionOnlyTitle: 'Branches with closed options only',
    optionOnlyBody: 'Every item is still orderable at these branches.',

    authSignInTitle: 'Sign in to your account',
    authSignUpTitle: 'Create your account',
    authSignIn: 'Sign In',
    authSignUp: 'Sign Up',
    authFullName: 'Full Name',
    authPhone: 'Phone (optional)',
    authEmail: 'Email',
    authPassword: 'Password',
    authWorking: 'Working…',
    authFailed: 'Authentication failed',

    // delivery-closure requests (branch asks, call centre answers)
    deliveryRequestSection: 'Delivery closure',
    requestCloseDelivery: 'Request delivery closed',
    requestCloseTitle: 'Request delivery closed',
    confirmRequest: 'Send request',
    withdrawRequest: 'Withdraw request',
    requestWaiting: 'Waiting for the call centre',
    requestWaitingHint: 'Delivery is still running. It stops only when the call centre accepts.',
    requestExpiresIn: 'Expires in',
    requestMinutesShort: 'm',
    requestAccepted: 'Your request was accepted',
    requestDeclined: 'Your request was not accepted',
    requestNoneTitle: 'No request waiting',
    requestNoneBody: 'If you cannot deliver, send a request to the call centre.',
    requestBlockedClosed: 'Delivery is already closed at your branch.',
    requestHint: 'Sending a request does not stop delivery. Only the call centre can.',
    requestSendFailed: 'The request could not be sent',

    // branch reference sheet
    referenceSection: 'Branch information',
    referenceEmptyTitle: 'Nothing saved yet',
    referenceEmptyBody: 'An administrator adds the numbers, links and logins you need here.',
    referenceReveal: 'Show',
    referenceHide: 'Hide',
    referenceRevealFailed: 'The value could not be shown',
    referenceAuditNotice: 'Every time a login is shown it is recorded — who showed it, and when.',
    referenceCopy: 'Copy',
    referenceCopied: 'Copied',

    // call-centre: answering a branch's delivery request
    requestsWaiting: 'Requests waiting',
    requestsNoneTitle: 'No requests waiting',
    requestFrom: 'Request from',
    requestAccept: 'Accept and close delivery',
    requestDecline: 'Decline',
    requestAnswerFailed: 'The request could not be answered',
    requestNowExpired: 'That request expired before it was answered',
    requestAskedFor: 'Asked for',
    reasonLabelShort: 'Reason',

    // ---- tabs (2026-09-16 redesign) ----
    tabItems: 'Items',
    tabGeneral: 'General',
    tabBranch: 'Branch info',
    tabDelivery: 'Delivery',

    // ---- items tab ----
    closedCount: 'items closed now',
    closedCountOne: 'item closed now',
    autoReopenNote: 'They reopen by themselves when the timer runs out',
    reopenAll: 'Reopen all at this branch',
    reopenAllTitle: 'Reopen every closed item?',
    reopenAllBody: 'Every closed item at your branch returns to the menu immediately. Other branches are not affected.',
    reopenAllConfirm: 'Yes, reopen all',
    reopenAllFailed: 'Some items could not be reopened',
    categoryAll: 'All',
    stateClosed: 'Closed',
    partiallyClosed: 'Partly closed',
    sizesCount: 'sizes',
    sizesCountOne: 'size',
    fromPrice: 'from',
    currency: 'SAR',

    // ---- variant sheet ----
    sizesTitle: 'Sizes and prices',
    sizesClosedOf: 'closed of',
    closeWholeItem: 'Close the whole item',
    done: 'Done',
    sizesPerSizeSoon: 'Closing a single size is not available yet — closing the item closes every size.',
    sizesAllClosed: 'Every size is closed — a customer cannot order this item.',
    sizesPerSizeOffReopenOnly: 'Closing a single size is switched off here, but sizes already closed can still be reopened.',
  },
} as const;

export type OpsStringKey = keyof typeof OPS_STRINGS['en'];

/** Look up copy, falling back to English so a missing Arabic key shows text rather than a key. */
export function opsT(lang: OpsLang, key: OpsStringKey): string {
  return OPS_STRINGS[lang][key] ?? OPS_STRINGS.en[key] ?? key;
}
