/** Geometric interface icons drawn with plain Views — no icon font/dependency. */
import React from 'react';
import { View, type ColorValue } from 'react-native';
interface IconProps { size?: number; color?: ColorValue; }
export function SearchIcon({size=18,color='#6b6580'}:IconProps){const ring=Math.round(size*.66),stroke=Math.max(2,Math.round(size/9));return <View style={{width:size,height:size}} pointerEvents="none"><View style={{width:ring,height:ring,borderRadius:ring/2,borderWidth:stroke,borderColor:color}}/><View style={{position:'absolute',bottom:0,right:0,width:Math.round(size*.42),height:stroke,borderRadius:stroke/2,backgroundColor:color,transform:[{rotate:'45deg'}]}}/></View>;}
export function HomeIcon({size=24,color='#6b6580'}:IconProps){const stroke=Math.max(2,Math.round(size/12)),roof=Math.round(size*.52),body=Math.round(size*.58);return <View style={{width:size,height:size,alignItems:'center'}} pointerEvents="none"><View style={{width:roof,height:roof,borderTopWidth:stroke,borderLeftWidth:stroke,borderColor:color,transform:[{rotate:'45deg'}],position:'absolute',top:Math.round(size*.06),borderTopLeftRadius:3}}/><View style={{position:'absolute',bottom:0,width:body,height:Math.round(size*.5),borderWidth:stroke,borderTopWidth:0,borderColor:color,borderBottomLeftRadius:3,borderBottomRightRadius:3}}/></View>;}
export function ReceiptIcon({size=24,color='#6b6580'}:IconProps){const stroke=Math.max(2,Math.round(size/12)),w=Math.round(size*.7),line={height:stroke,borderRadius:stroke/2,backgroundColor:color}as const;return <View style={{width:size,height:size,alignItems:'center',justifyContent:'center'}} pointerEvents="none"><View style={{width:w,height:Math.round(size*.86),borderWidth:stroke,borderColor:color,borderRadius:3,paddingHorizontal:Math.round(size*.12),justifyContent:'center',gap:Math.max(2,Math.round(size*.12))}}><View style={[line,{width:'100%'}]}/><View style={[line,{width:'100%'}]}/><View style={[line,{width:'60%'}]}/></View></View>;}
export function PersonIcon({size=24,color='#6b6580'}:IconProps){const stroke=Math.max(2,Math.round(size/12)),head=Math.round(size*.36),shoulders=Math.round(size*.62);return <View style={{width:size,height:size,alignItems:'center',justifyContent:'flex-end'}} pointerEvents="none"><View style={{width:head,height:head,borderRadius:head/2,borderWidth:stroke,borderColor:color,marginBottom:Math.max(1,Math.round(size*.06))}}/><View style={{width:shoulders,height:Math.round(shoulders*.52),borderTopLeftRadius:shoulders/2,borderTopRightRadius:shoulders/2,borderWidth:stroke,borderBottomWidth:0,borderColor:color}}/></View>;}
export function AlertIcon({size=40,color='#e02d3d'}:IconProps){const stroke=Math.max(2,Math.round(size/14)),barH=Math.round(size*.32);return <View style={{width:size,height:size,borderRadius:size/2,borderWidth:stroke,borderColor:color,alignItems:'center',justifyContent:'center',gap:Math.max(2,Math.round(size*.07))}} pointerEvents="none"><View style={{width:stroke,height:barH,borderRadius:stroke/2,backgroundColor:color,marginTop:Math.round(size*.1)}}/><View style={{width:stroke+1,height:stroke+1,borderRadius:stroke,backgroundColor:color,marginBottom:Math.round(size*.08)}}/></View>;}
export function CheckCircleIcon({size=48,color='#1f9d55'}:IconProps){const stroke=Math.max(2,Math.round(size/14)),checkW=Math.round(size*.42),checkH=Math.round(size*.24);return <View style={{width:size,height:size,borderRadius:size/2,borderWidth:stroke,borderColor:color,alignItems:'center',justifyContent:'center'}} pointerEvents="none"><View style={{width:checkW,height:checkH,borderLeftWidth:stroke,borderBottomWidth:stroke,borderColor:color,transform:[{rotate:'-45deg'}],marginTop:-Math.round(checkH*.4)}}/></View>;}
export function ClockIcon({size=48,color='#8a6d1f'}:IconProps){const stroke=Math.max(2,Math.round(size/14)),hourH=Math.round(size*.2),minuteW=Math.round(size*.24);return <View style={{width:size,height:size,borderRadius:size/2,borderWidth:stroke,borderColor:color,alignItems:'center',justifyContent:'center'}} pointerEvents="none"><View style={{position:'absolute',width:stroke,height:hourH,borderRadius:stroke/2,backgroundColor:color,top:size/2-hourH,left:size/2-stroke}}/><View style={{position:'absolute',width:minuteW,height:stroke,borderRadius:stroke/2,backgroundColor:color,top:size/2-stroke,left:size/2-stroke}}/></View>;}
export function AwardIcon({size=24,color='#422e87'}:IconProps){const stroke=Math.max(2,Math.round(size/12)),ring=Math.round(size*.58),core=Math.round(size*.2),legW=stroke+1,legH=Math.round(size*.34);return <View style={{width:size,height:size,alignItems:'center'}} pointerEvents="none"><View style={{width:ring,height:ring,borderRadius:ring/2,borderWidth:stroke,borderColor:color,alignItems:'center',justifyContent:'center'}}><View style={{width:core,height:core,borderRadius:core/2,backgroundColor:color}}/></View><View style={{flexDirection:'row',gap:Math.round(size*.14),marginTop:-2}}><View style={{width:legW,height:legH,borderRadius:legW/2,backgroundColor:color,transform:[{rotate:'16deg'}]}}/><View style={{width:legW,height:legH,borderRadius:legW/2,backgroundColor:color,transform:[{rotate:'-16deg'}]}}/></View></View>;}
export function SignOutIcon({size=20,color='#ffffff'}:IconProps){const stroke=Math.max(2,Math.round(size/10)),frameH=Math.round(size*.9),frameW=Math.round(size*.46),tip=Math.round(size*.3);return <View style={{width:size,height:size,justifyContent:'center'}} pointerEvents="none"><View style={{position:'absolute',left:0,width:frameW,height:frameH,borderWidth:stroke,borderRightWidth:0,borderColor:color,borderTopLeftRadius:4,borderBottomLeftRadius:4}}/><View style={{position:'absolute',left:Math.round(size*.3),right:Math.round(size*.12),height:stroke,borderRadius:stroke/2,backgroundColor:color}}/><View style={{position:'absolute',right:Math.round(size*.06),width:tip,height:tip,borderTopWidth:stroke,borderRightWidth:stroke,borderColor:color,transform:[{rotate:'45deg'}]}}/></View>;}
export function BagIcon({size=40,color='#c9c4d6'}:IconProps){const stroke=Math.max(2,Math.round(size/16)),bodyW=Math.round(size*.72),handleW=Math.round(size*.36);return <View style={{width:size,height:size,alignItems:'center',justifyContent:'flex-end'}} pointerEvents="none"><View style={{width:handleW,height:Math.round(handleW*.62),borderTopLeftRadius:handleW/2,borderTopRightRadius:handleW/2,borderWidth:stroke,borderBottomWidth:0,borderColor:color,marginBottom:-stroke}}/><View style={{width:bodyW,height:Math.round(size*.58),borderWidth:stroke,borderColor:color,borderTopLeftRadius:4,borderTopRightRadius:4,borderBottomLeftRadius:Math.round(size*.16),borderBottomRightRadius:Math.round(size*.16)}}/></View>;}
export function DishIcon({size=40,color='#c9c4d6'}:IconProps){const stroke=Math.max(2,Math.round(size/16)),inner=Math.round(size*.5);return <View style={{width:size,height:size,borderRadius:size/2,borderWidth:stroke,borderColor:color,alignItems:'center',justifyContent:'center'}} pointerEvents="none"><View style={{width:inner,height:inner,borderRadius:inner/2,borderWidth:stroke,borderColor:color}}/></View>;}
/** Map pin: teardrop outline with a solid centre. Used for branch directions. */
export function PinIcon({size=18,color='#e02d3d'}:IconProps){const stroke=Math.max(1.5,Math.round(size/9)),body=Math.round(size*.62),core=Math.max(3,Math.round(size*.2));return <View style={{width:size,height:size,alignItems:'center'}} pointerEvents="none"><View style={{width:body,height:body,borderRadius:body/2,borderWidth:stroke,borderColor:color,alignItems:'center',justifyContent:'center'}}><View style={{width:core,height:core,borderRadius:core/2,backgroundColor:color}}/></View><View style={{width:stroke*2,height:Math.round(size*.3),marginTop:-stroke,transform:[{rotate:'45deg'}],backgroundColor:color,borderBottomRightRadius:stroke}}/></View>;}
export function CrosshairIcon({size=20,color='#422e87'}:IconProps){const stroke=Math.max(1.5,Math.round(size/10)),ring=Math.round(size*.62),dot=Math.max(3,Math.round(size*.2)),tick=Math.max(2,Math.round(size*.14)),tickStyle={position:'absolute' as const,backgroundColor:color,borderRadius:stroke};return <View style={{width:size,height:size,alignItems:'center',justifyContent:'center'}} pointerEvents="none"><View style={{width:ring,height:ring,borderRadius:ring/2,borderWidth:stroke,borderColor:color,alignItems:'center',justifyContent:'center'}}><View style={{width:dot,height:dot,borderRadius:dot/2,backgroundColor:color}}/></View><View style={[tickStyle,{top:0,width:stroke,height:tick}]}/><View style={[tickStyle,{bottom:0,width:stroke,height:tick}]}/><View style={[tickStyle,{left:0,height:stroke,width:tick}]}/><View style={[tickStyle,{right:0,height:stroke,width:tick}]}/></View>;}
/** Delivery scooter: two wheels, deck, front stem and a delivery box. */
export function DeliveryIcon({size=40,color='#e02d3d'}:IconProps){const stroke=Math.max(2,Math.round(size/14)),wheel=Math.round(size*.22);return <View style={{width:size,height:size}} pointerEvents="none"><View style={{position:'absolute',left:Math.round(size*.08),bottom:Math.round(size*.06),width:wheel,height:wheel,borderRadius:wheel/2,borderWidth:stroke,borderColor:color}}/><View style={{position:'absolute',right:Math.round(size*.08),bottom:Math.round(size*.06),width:wheel,height:wheel,borderRadius:wheel/2,borderWidth:stroke,borderColor:color}}/><View style={{position:'absolute',left:Math.round(size*.18),right:Math.round(size*.19),bottom:Math.round(size*.18),height:stroke,backgroundColor:color,borderRadius:stroke}}/><View style={{position:'absolute',right:Math.round(size*.2),top:Math.round(size*.18),width:stroke,height:Math.round(size*.5),backgroundColor:color,borderRadius:stroke,transform:[{rotate:'-8deg'}]}}/><View style={{position:'absolute',right:Math.round(size*.08),top:Math.round(size*.14),width:Math.round(size*.22),height:stroke,backgroundColor:color,borderRadius:stroke}}/><View style={{position:'absolute',left:Math.round(size*.16),top:Math.round(size*.26),width:Math.round(size*.38),height:Math.round(size*.28),borderWidth:stroke,borderColor:color,borderRadius:4}}/></View>;}
