/** Spicy Meal logo lockup: brand mark + wordmark, shown at the top of screens. */
import { Image } from 'expo-image';
import React from 'react';
import { StyleSheet, View } from 'react-native';

import { space } from '../design-system/generated/tokens';
import { Text } from '../design-system/ui/Text';
import { makeStyles } from '../theme/makeStyles';

// The official production mark, with the master's white backdrop knocked out so
// it sits on the app's dark surfaces. Generated by `scripts/build-logo-mark.mjs`
// from the same artwork as the store icon, which stays opaque.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const MARK = require('../../assets/logo-mark.png');

export function Logo({ compact = false }: { compact?: boolean }) {
  const styles = useStyles();
  return (
    <View style={styles.row}>
      <Image source={MARK} style={compact ? styles.markSm : styles.mark} contentFit="contain" />
      {!compact && (
        <View>
          <Text variant="title">Spicy Meal</Text>
          <Text variant="caption" tone="ember">سبايسي ميل</Text>
        </View>
      )}
    </View>
  );
}

const useStyles = makeStyles((colors) => ({
  row: { flexDirection: 'row', alignItems: 'center', gap: space.s2 },
  // No corner radius: the mark is transparent now, so there is no tile to round.
  mark: { width: 40, height: 40 },
  markSm: { width: 30, height: 30 },
}));
